{% set name = "pybv" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9060eaa7950c94e36653ee68138e4662cd840d40e5c0e981f99240aab28f48a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - pybv
    - pybv.io

about:
  home: https://pybv.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A lightweight I/O utility for the BrainVision data format, written in Python
  dev_url: https://github.com/bids-standard/pybv

extra:
  recipe-maintainers:
    - hoechenberger
