travis:
  secure:
    BINSTAR_TOKEN: QFNACy1OkeXJ+443YHbZPc/qALFU3pFae84aL9slyg8Ohl+re1WALaCtuSLCcu73la9fi5c7fpDBsa5XBlMfHU/VwxXcBibdDqbnyqTC0Bi6GNU+78awiVYCQr5CEHegVCsTb5K3wgFGr+EOGQfI7iuk5oF8Hig12J24oVrMjwIacrgwTxwk7biH5sCshyAWAUoJrFex0QRSwtDdw38CihjtdjBN4M0ODU98KfSFUUJRY0qSGb1kc6x1v7dbXdqW7bWlmtgWfRl0YhaONeAA9u+wwP4tFZUxvMYJwHhpYyNX4dECGU6H9JNAdbCHPr8Gt+vjplgaUKvLQDfGU/5gJMfOSO00paZKtRo5SkUAXrDPeUuS/1Y8PJAKgvyOaJ2+jXpq+xyFQvzBPYub5kVUTcScfal2S+ndSG9zVn9KJ10xurX1GfOmovXSI5hJX5iHCnrZavmyAbYl6BC948yizaPzWdlskfHGI3g5mH8CZ4xaNYS7KCdgW8kEd+wDa1/cjV9ugfhGQBwSdpEDUja/aM2GOKu8H9cP1JXjeyr2kD1SJPNBr4HTaXnM8hrCczleX1guRpkhxUspPbP+UQ14SqxUmFlyY3NyUXUT74t2oa6B0a797WPEY+ZlWi7opMf8twp3mzJ629LPQu5bKfIq/S/KKtelSIC1OkyHPif7ipQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
