travis:
  secure:
    BINSTAR_TOKEN: luf8vDACknK99qs7GCmqJmsly3BB5PkwOo79GEufWETH6RdBT2LUc8te9wTRJSD6jscxuhXi5FZABvkM6zixLi2wp5uGVCaI+eYCOboS2WN2+FAYs+t4QSfKLhqdTy6ppQ1ZEE0NEwIAt3XW9NEBjZT8OJJGvWxKxad8rXGjYAHJ3E2cI7hzxCROpTE5hLg3nBbS1RUlCLnBFUTYURKLKKcQCG2MRwbZG4lIszBxUb0hqXy9JqSaTiz7NKNxPpy57gYfAYPRzkgzsK/kYLUJFjSxL+mtg4KDBl8qWnWZo+4GKUTdwHd6un/Snb22/wUsDiOZDmkJffhCPLTaHb+Qes4wtbqiI13IuCvDHO0x0PN70aQVx8udVMfjtU5FRE8Q8/Cgg4rz+R1J4PvFWhiJAeMah8F0/rgVtUyxeNjcqjc6KRoc58KNbSF8UKkgzrb8ncw2ULpMGf+9NZLEAWxDgV1lR5Ra+7aoipfzNu8szPnt+CCA7tpml5UBr4+xUuv/IIk8HSAC1MrJZB6Qh2eHxcwBDcENknq0UnGUvzslKbtUVXDPs+nLrYhPIysH2sr78FNBzCKgXgp6RtSB6zOc25rc3nCHRxLX7MBHPdja7YbmFn8H5RDowU6GAAHuU+JkimtPWVNt3jYizdN4xU0gfKZepboeG6d6EroPuPmyarQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
